### ISSUE TITLE
Error in session$sendInsertUI(selector = selector, multiple = multiple, attempt to apply non-function

### ISSUE THREAD

**Issue by doncqueurs** [Yang-Tang/shinyjqui#20]
I am quite interested in using the shinyjqui package to build some cool GUIs. Anyway, before I start using the package for the ideas I have in mind I am trying to get the simple stuff going. But something odd seems to happen. 

When I am using the very basic example from the homepage:

```
# load packages
library(shiny)
library(shinyjqui)
library(ggplot2)
library(highcharter)

server <- function(input, output) {}

ui <- fluidPage(
  jqui_draggable(fileInput('file', 'File'))
)

shinyApp(ui, server)
```

And when I try to run this, I get the following error code (and no working example):

> Error in session$sendInsertUI(selector = selector, multiple = multiple,  : 
>   attempt to apply non-function

I am using the most recent R release: R version 3.5.0 (2018-04-23). 

Appreciate if anybody can explain what it means and how I can mitigate the issue .

**Comment by Yang-Tang** [comment]
Hi @doncqueurs, I think the error was duo to the version of shinyjqui you installed. 
I made some changes to the package last month, but haven't pushed the update to CRAN yet. The examples showed in the github homepage only works in the new version. 
If you are using the shinyjqui from CRAN (version 0.2.0), you should use `jqui_draggabled()` instead of `jqui_draggable()` in this case. 
Sorry for the inconvenience.
