### ISSUE TITLE
Feature Request: updateOrderInput 

### ISSUE THREAD

**Issue by trafficonese** [Yang-Tang/shinyjqui#41]
It would be nice to have an `updateOrderInput `function for `orderInput` to order the items to the initial value for example or change the `item_class` / `connect` / etc..

This small example would reorder the items to the original values.
```
library(shiny)
library(shinyjqui)

ui <- fluidPage(
  orderInput('source', 'Source', items = LETTERS[1:5], as_source = F),
  verbatimTextOutput('order'),
  actionButton("update", "Update to initial order")
)

server <- function(input, output, session) {
  output$order <- renderPrint({ 
    print(input$source_order) 
  })
  observeEvent(input$update, {
    # updateOrderInput(session, "source", items = LETTERS[1:5])
  })
}

shinyApp(ui, server)
```

**Comment by rquitales** [comment]
There is a way to achieve this without modification to the package by using `uiOutput()` and `renderUI()`

I have updated your small example to showcase this:

```
library(shiny)
library(shinyjqui)

ui <- fluidPage(
  # Use uiOutput() to output shinyjqui object
  uiOutput('jqui_ui'),
  
  verbatimTextOutput('order'),
  actionButton("update", "Update to initial order")
)

server <- function(input, output, session) {
  output$order <- renderPrint({ 
    print(input$source_order) 
  })
  
  # Create shinyjqui output, and re-trigger when action button is clicked
  output$jqui_ui <- renderUI({
    input$update
    orderInput('source', 'Source', items = LETTERS[1:5], as_source = F)
  })
}

shinyApp(ui, server)
```

Hope this helps,
Ramon

**Comment by trafficonese** [comment]
Yes, like that I can reorder to the original, but I cannot set another `item_class` or change the `label` etc..

**Comment by R3myG** [comment]
I've given a try to write a wrapper around `session$sendInputMessage(inputId, message)` in order to create an updateOrderInput but it just wont work. 

The goal was to implement the option to move all the items on one side or the other.

**Comment by Yang-Tang** [comment]
Hi @trafficonese and @R3myG ,  `updateOrderInput` is now available in the latest GitHub version and will be included in the next CRAN submission. 
Originally, the `orderInput` function was not implemented as a shiny input binding, that's why `session$sendInputMessage(inputId, message)`  didn't work. With the update (eac9f1c815e39da49a6806d76e462b201d446071), the new version of `orderInput` should work in the same way as other shiny inputs.

**Comment by trafficonese** [comment]
Very nice, thank you very much for the work! 👍 

I still have a problem though. When I use `updateOrderInput` the matrix is filled with NA and I am not getting the values back inside. The example of `updateOrderInput` is working fine though.

But my original example fails somehow. I just want to reset the order to the original.

Do you know what could cause the NA`s ?

**Comment by Yang-Tang** [comment]
Sorry, I forgot to mention that, in order to keep the same style as other shiny inputs, the input value was changed from `input$inputId_order` to `input$inputId`. In your case, please use `input$source` to get the item order, meanwhile, a `legacy` argument was added to the new `orderInput` function for people who want to use the old style, but the old style one doesn't support `updateOrderInput`.
