### ISSUE TITLE
how can   jqui_resizable  resize on only one direction? e.g. vertical?

### ISSUE THREAD

**Issue by denchugen** [Yang-Tang/shinyjqui#59]
how can   jqui_resizable  resize on only one direction? e.g. vertical?

**Comment by trafficonese** [comment]
You can use the `handles` option.

The following allows only resizing the "south" side:
```
jqui_resizable(
  plotlyOutput("plot", height = "500px", width = "100%"),
  options = list(handles = "s")
)
```

Although I'm wondering how can we resize only vertical, but keep the width at 100%?

**Comment by ComeMaes** [comment]
I have an associated question:
regardless of the `handles`parameter setting, when I drag the handle in one direction it will also resize in the opposite direction, e.g. if I drag the top side of a panel up the panel will also be resized at the bottom, by an equal amount.

Is there any way to avoid such behaviour, so that the object is resized only in the direction where the handle is pulled?

Thanks

**Comment by m-swirski** [comment]
Hi, the solution provided doesn't work for me, please see the example (very slightly changed from default example):
```
library(shiny)
library(shinyjqui)
library(ggplot2)
server <- function(input, output) {
  output$gg <- renderPlot({
    ggplot(mtcars, aes(x = cyl, y = mpg)) + geom_point()
  })
}

ui <- fluidPage(
  jqui_resizable(plotOutput('gg'), options = list(handles = "s"))
)

shinyApp(ui, server)
```

If handles is set to "se" it just behave like normal jqui_rsizable. It doesnt matter if plotly or ggplot is used.

Thanks,
Michal
